language: java
jdk:
  - oraclejdk8

sudo: false
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-5
    - g++-5

env:
  - CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5
